services:
  backend:
    container_name: rqg-backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/usr/rqg/app
      - ./backend/scripts:/usr/rqg/scripts
      - /tmp/rqg:/tmp/rqg
    depends_on:
      - db

  db:
    image: postgres:17.2-bookworm
    container_name: rqg-db
    shm_size: 128mb
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    container_name: rqg-frontend
    build: ./frontend
    command: npm run dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
