services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/usr/rqg/app
      - ./backend/scripts:/usr/rqg/scripts
      - /tmp/rqg:/tmp/rqg
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/dev.Dockerfile
    command: npm run dev
    env_file: .env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend


  db:
    image: postgres:17.2-bookworm
    shm_size: 128mb
    env_file: .env.dev
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
